// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbaqwbhycdtjudyyxmge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYXF3Ymh5Y2R0anVkeXl4bWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExOTkxNTMsImV4cCI6MjA4Njc3NTE1M30.dOUSYOwW8YbranpsgQjErPhtJvL8ztZrktrT55txJps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});